name: Auto Tar

on:
  push:
    paths:
      - 'usr/**' # 监视 usr 文件夹及其子文件夹
      - 'etc/**' # 监视 tmp 文件夹及其子文件夹
    branches:
      - chinese_mainland  # 适当地更改分支名称
  # watch:
  #   types:
  #     - started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Run tar.sh and Upload
      run: |
        chmod -R 777 usr/
        chmod -R 777 etc/
        tar -pczvf tailscale-openwrt.tgz usr/ etc/ || tar c -pzvf tailscale-openwrt.tgz usr/ etc/
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "$(date -u +'%Y-%m-%d %H:%M:%S' -d '+8 hours')"
        git push origin HEAD:chinese_mainland
